import * as E from './engine.js';
import {enemyVisualGear} from './enemy-equipment.js';
import * as G from './gameplay-review.js';
import {EQUIPMENT_ART} from './equipment-art.js';
import {ACTS, ACT_LENGTH, CAMPAIGN_LENGTH} from './campaign.js';

const SAVE_KEY='exact-lethal-full-version-run-v1', PROFILE_KEY='exact-lethal-full-version-profile-v1', TELEMETRY_KEY='exact-lethal-full-version-telemetry-v1', SPEED_KEY='exact-lethal-full-version-animation-speed-v1';
const LEGACY_SAVE_KEY='exact-lethal-act1-v3';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storageOK=true;
function read(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
function hasStored(key){try{return localStorage.getItem(key)!==null}catch{return false}}
let profile=read(PROFILE_KEY)||{wins:[],runs:0,best:0,exact:0,finished:[]};
if(!Array.isArray(profile.wins))profile.wins=[];
let telemetry=read(TELEMETRY_KEY)||G.initialRunTelemetry();
const savedRun=read(SAVE_KEY);
let state=E.restoreRun(savedRun);
if(savedRun&&state&&savedRun.version<state.version){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));}catch{storageOK=false}}
const legacySaveAvailable=hasStored(LEGACY_SAVE_KEY);
let selected=0,hoverTarget=null,modal=null,attackTarget=-1,animTimer,toastTimer,draftPicks=[],inspectedTarget=0,toastToken=0,roundStatus=null,practiceOrigin=null,lastConsequence=null;
let selectedDifficulty=state?.difficulty||'pilgrim';
const demo=E.newRun(140923,'pilgrim');
let intro=!state,roundView=null,enemyBusy=false,playerBusy=false,playerStatus=null;
let animationSpeed=[1,2,0].includes(read(SPEED_KEY))?read(SPEED_KEY):1;
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
const logoTitle='E<span class="blood-x">X</span>ACT LETHAL';

function persist(){if(practiceOrigin)return;try{if(state)localStorage.setItem(SAVE_KEY,JSON.stringify(state));localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));localStorage.setItem(TELEMETRY_KEY,JSON.stringify(telemetry));}catch{storageOK=false}}
function recordMastery(s){profile.presentationUnlocks??=[];for(const card of G.masteryCards(s,telemetry,profile))if(card.complete&&!profile.presentationUnlocks.includes(card.id))profile.presentationUnlocks.push(card.id)}
function finishRecord(){if(practiceOrigin||!state||!['won','lost'].includes(state.phase))return;profile.finished??=[];if(profile.finished.includes(state.id))return;recordMastery(state);profile.finished.push(state.id);profile.runs=(profile.runs||0)+1;profile.exact=(profile.exact||0)+state.exact;profile.best=Math.max(profile.best||0,state.day);if(state.phase==='won')profile=E.recordWin(profile,state);profile.finished=profile.finished.slice(-100);persist()}
function toast(message){const el=$('#toast'),token=++toastToken;el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>{if(token!==toastToken)return;el.classList.remove('show');setTimeout(()=>{if(token===toastToken&&!el.classList.contains('show'))el.textContent=''},180)},2600)}
function active(){return roundView||state||demo}
function busy(){return enemyBusy||playerBusy}
function fmt(a,b){return a===b?String(a):`${a}–${b}`}
function damageHits(w){const hits=Math.max(1,Number(w?.hits||w?.hitCount)||1),damage=fmt(w?.damageMin||0,w?.damageMax||0);return `${w?.damageMin===w?.damageMax?damage:`(${damage})`}×${hits}`}
function kindIcon(k){if(/hammer|mace/.test(k))return 'hammer';if(/glaive|spear/.test(k))return 'glaive';if(/axe/.test(k))return 'axe';if(/leather|armor|plate|mail|cloak|shield|effigy/.test(k))return 'leather';if(/dagger|fang|needle|heart/.test(k))return 'dagger';return 'sword'}
function materialClass(w){return `material-${['ornate','infernal'].includes(w?.materialTier)?w.materialTier:'crude'}`}
function itemArtClass(w){return EQUIPMENT_ART[w?.id]?.className||''}
function heroArmorClass(body){if(!body)return 'hero-cloth hero-unarmored';const steel=body.tags?.includes('heavy')||['plate','chainmail'].includes(body.id);return `hero-armored ${steel?'hero-steel':'hero-leather'}`}
function weaponIcon(w){const defense=E.armorCategory(w),kind=defense==='body'?'plate':defense==='offhand'?'buckler':kindIcon(`${w?.kind||''} ${w?.id||''}`);return `<div class="weapon-icon item-${kind} ${itemArtClass(w)} ${materialClass(w)}" aria-hidden="true"></div>`}
function weaponStats(w){if(!w)return '';if(w.passive)return `<div class="weapon-stat blue" aria-label="${w.armor||0} armor">♢${w.armor>0?'+':''}${w.armor||0}</div><div class="weapon-stat gold">${E.armorCategory(w)==='body'?'BODY':'OFFHAND'}</div>`;const hits=Math.max(1,Number(w.hits||w.hitCount)||1);return `<div class="weapon-stat damage" aria-label="${fmt(w.damageMin,w.damageMax)} damage per hit, ${hits} ${hits===1?'hit':'hits'}">${damageHits(w)}</div><div class="weapon-stat cost" aria-label="${w.cost} energy">◆${w.cost}</div>`}
function blessingText(w){return (w?.blessings||[]).map(id=>E.BLESSINGS[id]?.name||id).join(' · ')}
function weaponDescription(w){return w?.desc||''}
function specialText(w){if(!w)return '';const parts=[];if(w.aoe)parts.push('All foes');if(w.pierce)parts.push('Pierces armor');if(w.shred)parts.push(`Shred ${w.shred}`);if(w.blessings?.length)parts.push(...w.blessings.map(id=>E.BLESSINGS[id]?.name||id));return parts.join(' · ')}
function weaponA11y(w){if(!w)return 'Empty equipment slot.';if(w.passive)return `${w.name}. ${w.armor||0} armor. ${E.armorCategory(w)==='body'?'Body armor':'Offhand'}.`;const parts=[`${w.name}. ${fmt(w.damageMin,w.damageMax)} damage per hit, ${w.hits||1} ${(w.hits||1)===1?'hit':'hits'}, ${w.cost} energy.`];if(w.aoe)parts.push('Hits all foes.');if(w.pierce)parts.push('Ignores armor.');if(w.shred)parts.push(`Removes ${w.shred} armor after each hit.`);for(const id of w.blessings||[]){const blessing=E.BLESSINGS[id];if(blessing)parts.push(`${blessing.name}: ${blessing.desc}`)}return parts.join(' ')}
function healing(n){return Math.min(active().maxHp-active().hp,Math.floor(n*(E.DIFFICULTIES[active().difficulty]?.healingMultiplier||1)))}
function stat(symbol,value,label,cls=''){return `<div class="stat" data-stat="${label.toLowerCase()}"><div class="value ${cls}">${symbol} ${value}</div><div class="stat-label">${label}</div></div>`}
function intentIcon(it){return it?.type==='attack'?'⚔':it?.type==='heal'?'✚':it?.type==='brace'?'♢':'◷'}
function intentLabel(it){return it?.type==='attack'?'ATTACK':it?.type==='heal'?'HEAL':it?.type==='brace'?'BRACE':'WAIT'}
function intendedText(it){return esc(it?.label||`${it?.type||'wait'} ${it?.value||''}`)}
function intentCompact(it){const value=Number.isFinite(it?.value)?it.value:'';if(it?.type==='heal')return `✚${value}`;if(it?.type==='brace')return `♢${value}`;if(it?.type!=='attack')return '◷';const label=String(it.label||'').toLowerCase();if(label.includes('bomb'))return `BOMB ${value}`;if(label.includes('execution'))return `EXECUTE ${value}`;if(label.includes('curse'))return `CURSE ${value}`;if(label.includes('berserk'))return `BERSERK ${value}`;if(label.includes('reflect'))return `REFLECT ${value}`;return `${it.pierce?'PIERCE ':'⚔'}${value}`}
const LATER_ART_KEYS=new Set(['facet-swarm','lattice-sentinel','hinge-idol','crown-cluster','burrowing-lens','geode-mender','prism-grazer','gloom-moth','twelve-faced-archon','cinder-imp','chain-thrall','brand-serf','furnace-brute','hook-fiend','pain-cherub','marrow-steward','oath-demon','vharzael-furnace-below']);
function enemyArtClass(e){const art=String(e?.art||e?.type||'orc');if(art==='boss')return 'boss';if(art==='shaman')return 'shaman';if(art==='knight')return 'knight';if(['goblin','assassin'].includes(art))return 'goblin';return LATER_ART_KEYS.has(art)?art:'orc'}
function enemyArt(e,day){const gear=enemyVisualGear(e.type,day);return `<div class="monster sprite character-${enemyArtClass(e)} ${gear.length?'catalog-equipped':''}" aria-hidden="true">${gear.map(g=>{const w=E.WEAPONS[g.id],kind=w.defenseSlot==='body'?'plate':w.defenseSlot==='offhand'?'buckler':kindIcon(`${w.kind} ${w.id}`);return `<span class="enemy-gear enemy-${g.slot} weapon-icon item-${kind} ${itemArtClass(w)}" data-item-id="${esc(g.id)}"></span>`}).join('')}</div>`}
function heroArt(){const s=active(),items=s.slots.map((_,i)=>E.getWeapon(s,i)).filter(Boolean),body=items.find(w=>E.armorCategory(w)==='body'),offhand=items.find(w=>E.armorCategory(w)==='offhand');let weapon=E.getWeapon(s,selected);if(!weapon||weapon.passive)weapon=items.find(w=>!w.passive);const kind=weapon?kindIcon(`${weapon.kind} ${weapon.id}`):'';return `<div class="hero ${attackTarget>=0?'striking':''} ${body?`body-${materialClass(body)}`:''}" role="img" aria-label="The Wanderer, ${body?`wearing ${esc(body.name)}`:'unarmored'}${weapon?`, holding ${esc(weapon.name)}`:''}${offhand?`, with ${esc(offhand.name)}`:''}"><div class="hero-figure"><div class="sprite hero-base ${heroArmorClass(body)}"></div>${body?`<div class="hero-bodygear weapon-icon item-plate ${itemArtClass(body)} ${materialClass(body)}" aria-hidden="true"></div>`:''}${offhand?`<div class="hero-offhand weapon-icon item-buckler ${itemArtClass(offhand)} ${materialClass(offhand)}" aria-hidden="true"></div>`:''}${weapon?`<div class="hero-mainhand weapon-icon item-${kind} held-${kind} ${itemArtClass(weapon)} ${materialClass(weapon)}" aria-hidden="true"></div>`:''}</div><span class="hero-name">The Wanderer</span></div>`}
function energyOrb(s){const max=s.maxEnergy||3;return `<div class="energy-pool" role="meter" aria-label="Energy" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${s.energy}"><div class="energy-orb"><div class="energy-liquid" style="height:${100*s.energy/max}%"></div><span class="orb-value">${s.energy}<small> / ${max}</small></span></div><div class="energy-pips">${Array.from({length:max},(_,i)=>`<i class="${i<s.energy?'lit':''}"></i>`).join('')}</div><span class="energy-label">ENERGY</span></div>`}
function targetPreview(s,i){const w=E.getWeapon(s,selected),p=E.preview(s,selected,i);if(!w||w.passive||!p)return {tone:'muted',short:'SELECT GEAR',aria:'Select an active weapon to preview this target.'};const target=s.enemies[p.target??i],redirect=p.redirected?`Intercepted by ${target.name}. `:'';if(!p.affordable)return {tone:'warning',short:p.jammed?'JAMMED':'NEED ENERGY',aria:`${w.name} cannot attack: ${p.jammed?'weapon jammed':'not enough energy'}.`};if(p.cancelledByTrap||p.trapDamage>=s.hp)return {tone:'warning',short:`FATAL TRAP · −${p.trapDamage}`,aria:`Using ${w.name} triggers ${p.trapDamage} trap damage and defeats the Wanderer before the attack.`};const trap=p.trapDamage?` · TRAP −${p.trapDamage}`:'';if(p.exact)return {tone:'exact',short:`EXACT${trap}`,aria:`${redirect}${w.name} deals exact lethal to ${target.name}.${p.trapDamage?` Trap deals ${p.trapDamage} damage first.`:''}`};if(p.overkill)return {tone:'overkill',short:`OVERKILL · ${fmt(p.min,p.max)}${trap}`,aria:`${redirect}${w.name} deals ${fmt(p.min,p.max)} damage and overkills ${target.name}.${p.trapDamage?` Trap deals ${p.trapDamage} damage first.`:''}`};const exact=Math.round(p.exactChance*100),overkill=Math.round(p.overkillChance*100),odds=exact||overkill?`◎${exact}% · OV${overkill}%`:'SET UP';return {tone:p.trapDamage?'warning':'setup',short:`${fmt(p.min,p.max)} · ${odds}${trap}`,aria:`${redirect}${w.name} deals ${fmt(p.min,p.max)} total damage to ${target.name}, with ${exact} percent exact lethal and ${overkill} percent overkill.${p.trapDamage?` Trap deals ${p.trapDamage} damage first.`:''}`}}
function deathRemains(e){if(!e?.dead)return '';if(e.finish==='exact')return `<span class="death-remains exact-remains ${e.resolvedDrop?.type==='item'?'reward-item':'reward-gold'}" aria-hidden="true"></span>`;return '<span class="death-remains overkill-remains" aria-hidden="true"></span>'}
function finalOutcomeHTML(s){const dead=(s?.enemies||[]).filter(e=>e.dead);if(!dead.length)return '';return `<div class="final-outcome-art" aria-label="Battle outcomes">${dead.map(e=>`<span class="outcome-unit"><span class="sr-only">${esc(e.name)}: ${e.finish==='exact'?e.resolvedDrop?.type==='item'?'exact lethal, item reward':'exact lethal, gold reward':'overkill, no reward'}</span>${deathRemains(e)}</span>`).join('')}</div>`}
function enemiesHTML(s){return s.enemies.map((e,i)=>{const preview=targetPreview(s,i),disabled=e.dead||s.phase!=='combat'||busy(),imminent=e.mechanic==='headsman'&&!e.interrupted&&e.turnHits===e.interruptHits-1;return `<div class="enemy foe-${esc(e.type)} ${e.dangerous?'dangerous-foe':''} ${esc(e.art||e.type)} ${imminent?'counter-imminent':''} ${e.dead?`dead finish-${esc(e.finish||'unknown')}`:''} ${hoverTarget===i?'targeted':''} ${attackTarget===i?'attack-flash':''}" data-target="${i}">
 <div class="enemy-info"><div class="enemy-health" aria-label="${e.hp} of ${e.maxHp} health"><span>${e.hp}</span>/${e.maxHp}</div><div class="health-track" aria-hidden="true"><i class="health-fill" style="width:${Math.max(0,e.hp/e.maxHp*100)}%"></i></div>${e.dead?`<span class="finish-tag">${e.finish==='exact'?'EXACT':'OVERKILL'}</span>`:`<div class="intention ${e.intent?.type==='attack'?'red':e.intent?.type==='heal'?'green':'blue'}" aria-label="Next action: ${esc(e.intent?.label||intentLabel(e.intent))}"><b>${esc(intentCompact(e.intent))}</b></div>`}<div class="enemy-actions ${e.dead?'dead-actions':''}"><button data-action="inspect" data-target="${i}" aria-label="Inspect ${esc(e.name)}">Inspect</button></div></div>
 <button class="monster-target" data-action="attack" data-target="${i}" aria-label="${e.dead?`${esc(e.name)} defeated by ${e.finish==='exact'?'exact lethal':'overkill'}`:`Attack ${esc(e.name)}. Health ${e.hp} of ${e.maxHp}. ${esc(preview.aria)} ${esc(e.intent?.label)}`}" ${disabled?'disabled':''}>${e.dead?deathRemains(e):`${enemyArt(e,s.day)}<span class="target-ring"></span>`}</button></div>`}).join('')}
function hint(s){
 if(playerBusy)return playerStatus?.text||'Strike';
 if(enemyBusy)return 'Enemy round';
 if(s.phase!=='combat')return '';
 if(lastConsequence)return lastConsequence;
 const w=E.getWeapon(s,selected);
 if(s.jammedSlots?.includes(selected))return '⊘ JAMMED · choose gear';
 if(hoverTarget!==null)return targetPreview(s,hoverTarget).short;
 if(s.energy===0)return '0◆ · END TURN';
 const trapped=s.enemies.filter(e=>!e.dead&&e.trappedSlot===selected);
 return w&&!w.passive?`${damageHits(w)} · ◆${w.cost} · ${trapped.length?'⚠ TRAPPED':'choose target'}`:'Choose gear';
}
function slotWarnings(s,i){const jammed=s.jammedSlots?.includes(i),trapped=s.enemies.some(e=>!e.dead&&e.trappedSlot===i);return `${jammed?'<span class="slot-warning jammed">⊘ JAMMED</span>':''}${trapped?'<span class="slot-warning trapped">⚠ TRAPPED</span>':''}`;}
function equipmentHTML(s){return s.slots.map((uid,i)=>{const w=E.getWeapon(s,i),usable=E.canUse(s,i),special=specialText(w),label=`Select ${weaponA11y(w)}`;return `<button class="weapon-card ${selected===i?'selected':''} ${w?.passive?'passive':''} ${!usable?'unusable':''}" data-action="select" data-slot="${i}" ${busy()?'disabled':''} title="${esc(label)}" aria-label="${esc(label)}" aria-pressed="${selected===i}"><span class="hotkey">${'QWER'[i]}</span>${w?weaponIcon(w):'<span class="open-slot" aria-hidden="true">◇</span>'}<div class="weapon-meta"><div class="weapon-name sr-only">${esc(w?.name||'Empty slot')}</div>${w?weaponStats(w):'<div class="weapon-stat muted">EMPTY</div>'}${special?`<div class="weapon-special">${esc(special)}</div>`:''}${slotWarnings(s,i)}</div></button>`}).join('')}
function roundStatusHTML(){if(!roundStatus)return '';const label=roundStatus.busy?`Enemy ${roundStatus.index}/${roundStatus.total}`:'Round complete';return `<div id="round-status" class="round-status ${roundStatus.busy?'active':'complete'}" role="status" aria-live="polite"><b>${roundStatus.busy?'◷':'✓'} ${label}</b><span>${esc(roundStatus.text||roundStatus.summary||'')}</span></div>`}
function motionLabel(){return reducedMotion.matches?'Motion off':animationSpeed?`Motion ${animationSpeed}×`:'Motion off'}
function playerStatusHTML(){if(!playerStatus)return '';return `<div id="player-status" class="round-status player-status ${playerBusy?'active':'complete'}" role="status" aria-live="polite"><b>${playerBusy?'⚔':'✓'} ${playerBusy?`Hit ${playerStatus.index}/${playerStatus.total}`:'Strike complete'}</b><span>${esc(playerStatus.text||'')}</span></div>`}
function comparisonHTML(comparison){if(!comparison)return '';return `<div class="item-comparison" aria-label="${esc(`${comparison.name}. ${comparison.comparison}. ${comparison.interaction||''}`)}"><b>${esc(comparison.comparison)}</b>${comparison.currentRoom?`<em>Exact ${esc(comparison.currentRoom.oldExact||'—')}→${esc(comparison.currentRoom.newExact)}</em>`:''}${comparison.interaction?`<small>${esc(comparison.interaction)}</small>`:''}</div>`}
function reflectionHTML(s){const room=s?.history?.filter(entry=>entry.kills!==undefined).at(-1);if(!room||room.day!==s.day)return '';const reflection=G.campReflection(s,telemetry);if(!reflection)return '';return `<div class="compact-reflection" aria-label="Room reflection">${reflection.metrics.map(metric=>`<span><b>${esc(metric.value)}</b>${esc(metric.label)}</span>`).join('')}</div>`}
function actNumeral(act){return ['I','II','III'][act-1]||String(act)}
function campaignView(s){
 const dayNumber=Math.min(CAMPAIGN_LENGTH,Math.max(1,Number(s?.day)||1));
 const derivedAct=Math.ceil(dayNumber/ACT_LENGTH),currentAct=[1,2,3].includes(s?.campaign?.act)?s.campaign.act:derivedAct;
 const act=ACTS[currentAct-1]||ACTS[0],actDay=Math.min(ACT_LENGTH,Math.max(1,Number(s?.campaign?.actDay)||dayNumber-(currentAct-1)*ACT_LENGTH));
 const days=E.DAYS.filter(day=>day.act===currentAct||day.day>=(currentAct-1)*ACT_LENGTH+1&&day.day<=currentAct*ACT_LENGTH);
 return {dayNumber,currentAct,act,actDay,days};
}
function timelineHTML(s,campaign){return campaign.days.map((day,index)=>{const localDay=day.actDay||index+1,boss=day.type==='boss';return `<div class="day-node ${s.day===day.day?'current':s.day>day.day?'past':''}" title="Day ${day.day} · Act ${actNumeral(campaign.currentAct)} day ${localDay}: ${esc(day.name)}"><i><span>${day.type==='event'?'✦':boss?'♜':localDay}</span></i><em>${day.type==='event'?'Event':boss?'Boss':''}</em></div>`}).join('')}
function masteryHTML(s){return `<div class="mastery-cards" aria-label="Optional mastery contracts">${G.masteryCards(s,telemetry,profile).map(card=>`<article class="${card.complete?'complete':''}"><span>${card.complete?'✓':'◇'}</span><b>${esc(card.label)}</b><small>${card.progress}/${card.goal} · ${esc(card.reward)}</small></article>`).join('')}</div>`}
function render(){
 const s=active(),day=E.DAYS.find(d=>d.day===s.day)||{name:'The ruined road'},campaign=campaignView(s);
 $('#app').innerHTML=`<main class="shell ${(profile.presentationUnlocks||[]).map(id=>`mastery-${esc(id)}`).join(' ')}"><div class="frame"><header class="topbar"><div class="brand"><span class="sigil">✥</span>${logoTitle}</div><div class="act"><span class="eyebrow">Act ${actNumeral(campaign.currentAct)} · ${esc(campaign.act.title)}</span><span class="serif">Day ${campaign.dayNumber} / ${CAMPAIGN_LENGTH} <span class="muted">· Act day ${campaign.actDay}</span></span></div><div class="stats">${stat('♥',`${s.hp}<span class="muted">/${s.maxHp}</span>`,'Health','red')}${stat('♢',E.getArmor(s),'Armor')}${stat('◉',s.gold,'Gold','gold')}<button class="minor-button" data-action="menu" aria-label="Open game menu">Menu</button><button class="icon-button" data-action="help" aria-label="How to play">?</button></div></header>
 <nav class="timeline" aria-label="Act ${actNumeral(campaign.currentAct)} progress, days ${campaign.act.startDay} to ${campaign.act.endDay}">${timelineHTML(s,campaign)}</nav>
 <section class="stage" data-act="${campaign.currentAct}" aria-label="Battlefield"><div class="stage-heading"><span class="eyebrow">${esc(E.DIFFICULTIES[s.difficulty]?.name||'Pilgrim')}</span><h2>${esc(day.name)}</h2></div><span class="turn-tag">${enemyBusy?'ENEMY ROUND':playerBusy?'STRIKING':s.phase==='combat'?`TURN ${s.turn}`:'ROAD'}</span>${energyOrb(s)}${heroArt()}<div class="enemy-row">${enemiesHTML(s)}</div>${playerBusy?'':roundStatusHTML()}${playerStatusHTML()}<div class="combat-message"><span id="combat-hint">${esc(hint(s)||'Select · target · end')}</span></div></section>
 <section class="equipment" aria-label="Equipment">${equipmentHTML(s)}<button class="end-turn" data-action="end-turn" ${s.phase!=='combat'||busy()?'disabled':''}>${enemyBusy?'Enemy round':playerBusy?'Striking':'End Turn'}<small>SPACE ↵</small></button></section></div>
 <div class="underbar"><button class="minor-button" data-action="inventory">Gear</button><button class="minor-button speed-toggle" data-action="speed" title="Cycle motion speed: normal, fast, off" aria-label="${motionLabel()}">${motionLabel()}</button><span class="save">${storageOK?'◈ Saved':'Save off'}</span></div>
 </main>`;
 renderOverlay();
}
function modalWrap(content,classes=''){return `<div class="screen-shade"><section class="modal ${classes}" role="dialog" aria-modal="true">${content}</section></div>`}
function closeButton(){return '<button class="icon-button close" data-action="close" aria-label="Close dialog">×</button>'}
function header(title,desc='',eye=''){return `<div class="modal-header">${eye?`<span class="eyebrow">${eye}</span>`:''}<h2>${title}</h2>${desc?`<p>${desc}</p>`:''}</div>`}
function difficultyHTML(){const open=E.availableDifficulties(profile).map(d=>typeof d==='string'?d:d.id);return Object.values(E.DIFFICULTIES).map(d=>`<button class="difficulty-node ${!d.parent?'root':''} ${open.includes(d.id)?'':'locked'} ${selectedDifficulty===d.id?'selected':''}" data-action="difficulty-select" data-id="${d.id}" ${open.includes(d.id)?'':'disabled'}><span class="eyebrow">${d.parent?`↳ ${esc(E.DIFFICULTIES[d.parent]?.name)}`:'Starting path'}</span><h3>${esc(d.name)} ${profile.wins.includes(d.id)?'✓':''}</h3><p>${esc(d.desc)}</p>${d.id!=='pilgrim'?'<span class="danger-pool">Dangerous encounters enabled</span>':'<span class="safe-pool">Standard encounter pool</span>'}<small>${open.includes(d.id)?selectedDifficulty===d.id?'Selected':'Available':`Win ${esc(E.DIFFICULTIES[d.parent]?.name)} to unlock`}</small></button>`).join('')}
function introHTML(){return `<h1>${logoTitle}</h1><div class="actions"><button class="button primary" data-action="start">Begin</button><button class="button" data-action="difficulty" disabled aria-label="Difficulty locked"><span aria-hidden="true">🔒</span> Difficulty</button></div>`}
function itemFromDrop(drop){return E.effectiveWeapon(drop?.type==='chance'?drop.item:drop)}
function rewardHTML(e){
 const drop=e.drop,w=itemFromDrop(drop),random=drop?.type==='chance';
 const result=e.resolvedDrop;
 const odds=random?`<div class="reward-odds"><div><span class="reward-coin">◉</span><strong>${Math.round((1-drop.itemChance)*100)}%</strong><span>${drop.gold} gold</span></div><div><span class="reward-sigil">✦</span><strong>${Math.round(drop.itemChance*100)}%</strong><span>One item</span></div></div>`:'';
 const special=specialText(w);
 return `<h3 class="section-title">Exact loot</h3>${odds}${w?`<article class="inspect-drop">${weaponIcon(w)}<div>${random?'<span class="eyebrow">ITEM ROLL</span>':''}<h3>${esc(w.name)}</h3>${weaponStats(w)}${special?`<p>${esc(special)}</p>`:''}</div></article>`:''}${result?`<p class="reward-result">${result.type==='gold'?`◉ +${result.value}`:`✦ ${esc(E.WEAPONS[result.id]?.name||'Equipment')}`}</p>`:''}<p class="inspect-note">Exact: reward · overkill: none</p>`;
}
function inspectHTML(){const e=active().enemies[inspectedTarget];if(!e)return header('Enemy unavailable');return closeButton()+header(esc(e.name),'',e.dangerous?'DANGEROUS':'INSPECT')+`<div class="inspect-stats"><span>♥ <b>${e.hp}/${e.maxHp}</b></span><span>♢ <b>${e.armor}</b></span>${e.dead?'':`<span>${intentIcon(e.intent)} <b>${intentLabel(e.intent)}</b></span>`}</div>${e.traitText?`<div class="inspect-mechanic"><span class="eyebrow">SPECIAL</span><p>${esc(e.traitText)}</p></div>`:''}${e.dead?`<div class="inspect-mechanic"><span class="eyebrow">DEFEATED</span><p>${e.finish==='exact'?'Exact lethal.':'Overkill.'}</p></div>`:`<div class="inspect-mechanic"><span class="eyebrow">NEXT</span><p>${intendedText(e.intent)}</p>${e.counterText?`<p class="counter-detail ${e.interrupted?'counter-broken':''}">${esc(e.counterText)}</p>`:''}</div>`}${rewardHTML(e)}<div class="actions"><button class="button primary" data-action="close">Back</button></div>`}
function firstStepsHTML(){return `<div class="first-steps" aria-label="First battle steps"><span><b>1</b><i>⚔</i>Select</span><span><b>2</b><i>◎</i>Target</span><span><b>3</b><i>◷</i>End</span><small>HP 5 − 5 = <strong>EXACT</strong> · HP 4 − 5 = overkill</small></div>`}
function draftHTML(){return header('Choose 2','', 'STARTING GEAR')+`<div class="draft-grid">${state.startingChoices.map((item,i)=>{const w=itemFromDrop(item),pick=draftPicks.indexOf(i),special=specialText(w);return `<button class="draft-item ${pick>=0?'picked':''}" data-action="draft-pick" data-index="${i}" aria-label="${esc(`${w.name}. ${weaponDescription(w)}`)}" aria-pressed="${pick>=0}">${weaponIcon(w)}<div><h3>${esc(w.name)}</h3>${weaponStats(w)}${special?`<p>${esc(special)}</p>`:''}</div><span class="draft-mark">${pick>=0?'QW'[pick]:'+'}</span></button>`}).join('')}</div><div class="draft-summary"><span>${draftPicks.length}/2</span><span>♥${state.maxHp} · ◆3 · ◇◇</span></div><div class="actions"><button class="button primary" data-action="draft-confirm" ${draftPicks.length!==2?'disabled':''}>Take road →</button><button class="button" data-action="help">Details</button></div>`}
function dropsToday(s){
 if([3,7].includes(s.day))return '';
 const drops=(s.dropHistory||[]).filter(d=>d.day===s.day),gold=drops.filter(d=>d.type==='gold').reduce((sum,d)=>sum+d.value,0),items=drops.filter(d=>d.type!=='gold');
 return `<div class="camp-drops"><span class="eyebrow">LOOT</span>${gold?`<span>◉ +${gold}</span>`:''}${items.map(d=>`<span class="${d.status==='left'?'muted':''}">${esc(E.WEAPONS[d.id]?.name||d.id)}${d.blessings?.length?' ✦':''}${d.status==='left'?' · left':''}</span>`).join('')}${!drops.length?'<span class="muted">None</span>':''}</div>`
}
function inventoryHTML(){const s=active();return header('Equipment','4 slots · 1 body · 1 offhand','INSPECT')+`<div class="inventory-grid">${s.slots.map((uid,slot)=>{const w=E.getWeapon(s,slot);return `<article class="bag-item equipped">${w?weaponIcon(w):'<span class="open-slot">◇</span>'}<div><h3><small class="gold">[${'QWER'[slot]}]</small> ${esc(w?.name||'Empty')}</h3>${w?`${weaponStats(w)}${specialText(w)?`<p>${esc(specialText(w))}</p>`:''}`:'<p>Empty</p>'}</div></article>`}).join('')}</div><div class="actions"><button class="button primary" data-action="close">Done</button></div>`}
function overflowHTML(s){const drop=s.pendingDrops[0],w=itemFromDrop(drop),category=E.armorCategory(w),matching=s.slots.findIndex((_,i)=>category&&E.armorCategory(E.getWeapon(s,i))===category),target=s.enemies?.find(e=>!e.dead)?.id;return header('Carry it?','4 slots · 1 body · 1 offhand',esc(drop.source||'RECOVERED'))+`<article class="inspect-drop new-drop">${weaponIcon(w)}<div><span class="eyebrow">NEW</span><h3>${esc(w.name)}</h3>${weaponStats(w)}${specialText(w)?`<p>${esc(specialText(w))}</p>`:''}</div></article><div class="replacement-grid">${s.slots.map((uid,i)=>{const old=E.getWeapon(s,i),blocked=!E.canResolveDrop(s,i),comparison=G.compareItem(s,drop,{slot:i,targetIndex:target});return `<button class="replacement-item" data-action="resolve-drop" data-slot="${i}" aria-label="${esc(`${old?'Replace '+old.name:'Equip in empty slot'}. ${comparison?.comparison||''}`)}" ${blocked?'disabled':''}>${old?weaponIcon(old):'<span class="open-slot">◇</span>'}<div><span class="eyebrow">${'QWER'[i]} · ${old?'REPLACE':'EQUIP'}</span><h3>${esc(old?.name||'Empty')}</h3>${comparisonHTML(comparison)}${blocked?`<p>${matching>=0&&matching!==i?'Use matching slot':'Keep a weapon'}</p>`:''}</div></button>`}).join('')}</div><div class="actions"><button class="button" data-action="leave-drop">Leave</button><span class="muted">${s.pendingDrops.length} pending</span></div>`}
function renderOverlay(){
 const s=state;
 if(busy()){$('#overlay').innerHTML='';return;}
 if(modal==='help'){$('#overlay').innerHTML=modalWrap(closeButton()+header('Exact lethal','Select gear, read the target preview, then strike.','DETAILS')+`<div class="help-rows"><div><h3>⚔ Gear</h3><p><span class="inline-key">Q W E R</span> selects reusable gear. Damage is shown as damage × hits; ◆ is energy. Armor reduces each hit unless the weapon pierces.</p></div><div><h3>◎ Finish</h3><p>Damage exactly equal to remaining health earns one reward: 80% gold, 20% equipment. Overkill earns none. Every enemy panel shows the current exact/overkill chance for keyboard, touch, and pointer play.</p></div><div><h3>◷ Enemy round</h3><p>Living enemies act left to right after End Turn. Intent labels, counters, traps, and jams remain visible. Inspect holds full special rules.</p></div><div><h3>◇ Campaign</h3><p>Carry your gear and gold through three ten-day acts: the Ashen Road, The Crystal Below, and Pits of Hell. Events fall on act-days 3 and 7; bosses on act-day 10. Days 10 and 20 are milestones. Day 30 is the final victory.</p></div></div><div class="actions"><button class="button primary" data-action="close">Done</button></div>`);return;}
 if(modal==='difficulty'){$('#overlay').innerHTML=modalWrap(closeButton()+header('The burden tree','Each victory opens a more difficult path. Nothing here makes your character stronger.','DIFFICULTY')+`<div class="difficulty-tree">${difficultyHTML()}</div><div class="actions"><button class="button primary" data-action="close">${state?'Back':'Choose this path'}</button></div>`);return;}
 if(modal==='inspect'){$('#overlay').innerHTML=modalWrap(inspectHTML());return;}
 if(modal==='inventory'){$('#overlay').innerHTML=modalWrap(closeButton()+inventoryHTML());return;}
 if(modal==='menu'){$('#overlay').innerHTML=modalWrap(closeButton()+header('Menu',storageOK?'◈ Saved':'Save unavailable')+`<div class="actions"><button class="button primary" data-action="close">Return</button><button class="button" data-action="difficulty">Difficulty</button><button class="button" data-action="help">Details</button><button class="button danger" data-action="restart-confirm">Abandon</button></div>`);return;}
 if(modal==='restart'){$('#overlay').innerHTML=modalWrap(header('Leave this run behind?','Your current equipment and progress will be lost. Difficulty unlocks remain.')+`<div class="actions"><button class="button danger" data-action="abandon">Abandon run</button><button class="button" data-action="close">Keep playing</button></div>`);return;}
 if(intro){$('#overlay').innerHTML=modalWrap(introHTML(),'intro');return;}
 if(!s){$('#overlay').innerHTML='';return;}
 if(practiceOrigin&&s.phase!=='combat'){$('#overlay').innerHTML=modalWrap(header(s.phase==='lost'?'Practice failed':'Practice complete','Live run unchanged','PRACTICE')+finalOutcomeHTML(s)+`<div class="actions"><button class="button primary" data-action="exit-practice">Return to run</button></div>`,'practice-result');return;}
 if(s.phase==='draft'){$('#overlay').innerHTML=modalWrap(draftHTML(),'draft-modal');return;}
 if(s.pendingDrops?.length&&['camp','event','milestone','won'].includes(s.phase)){$('#overlay').innerHTML=modalWrap(overflowHTML(s),'overflow-modal');return;}
 if(s.phase==='camp'){const next=E.DAYS.find(d=>d.day===s.day+1);$('#overlay').innerHTML=modalWrap(header(`Day ${s.day} clear`,'','ROAD')+finalOutcomeHTML(s)+reflectionHTML(s)+`<p class="next-threat">Next · <span class="gold">${esc(next?.name||'Road')}</span></p>${dropsToday(s)}<div class="actions"><button class="button primary" data-action="next-day">Day ${s.day+1} →</button><button class="button" data-action="inventory">Gear</button></div>`);return;}
 if(s.phase==='event'){$('#overlay').innerHTML=modalWrap(header(esc(s.event.title),'','DAY '+s.day)+`<div class="choice-grid shop-grid">${s.event.options.map((o,i)=>{const w=o.item?E.effectiveWeapon({id:o.item,blessings:o.blessings||[]}):null,comparison=w?G.compareItem(s,{id:o.item,blessings:o.blessings||[]}):null,visibleLabel=w?w.name:o.label,detail=o.heal?`Restore ${healing(o.heal)} health.`:o.desc;return `<button class="choice" data-action="event" data-index="${i}" aria-label="${esc(`${visibleLabel}. ${detail}. ${o.cost?`${o.cost} gold`:''}`)}" ${o.disabled||(o.cost&&s.gold<o.cost)?'disabled':''}>${w?weaponIcon(w):o.heal?'<span class="big-symbol">♥</span>':''}<h3>${esc(visibleLabel)}</h3>${w?`${weaponStats(w)}${specialText(w)?`<p>${esc(specialText(w))}</p>`:''}${comparisonHTML(comparison)}`:`<p>${o.heal?`+${healing(o.heal)} HP`:esc(o.desc)}</p>`}<span class="caption">${o.disabled?'BOUGHT':o.cost?`◉${o.cost} · have ${s.gold}`:o.id==='leave'?'LEAVE':'CHOOSE'}</span></button>`}).join('')}</div><div class="actions"><button class="button" data-action="inventory">Gear</button></div>`);return;}
 if(s.phase==='milestone'){const campaign=campaignView(s),transition=s.campaign?.transition,nextAct=ACTS[(transition?.toAct||campaign.currentAct+1)-1];$('#overlay').innerHTML=modalWrap(`<span class="ending-mark" aria-hidden="true"></span>`+header(`Act ${actNumeral(campaign.currentAct)} complete`,`Day ${s.day} milestone`,esc(campaign.act.title).toUpperCase())+finalOutcomeHTML(s)+reflectionHTML(s)+`<p class="next-threat">Next · <span class="gold">Act ${actNumeral(nextAct?.act||campaign.currentAct+1)} · ${esc(nextAct?.title||'Unknown road')}</span></p><p class="inspect-note">Continue with full HP (${s.maxHp}/${s.maxHp}). Your gear, gold, and boss rewards carry forward.</p>${dropsToday(s)}<div class="actions"><button class="button primary" data-action="continue-act">Restore full HP · Enter Act ${actNumeral(nextAct?.act||campaign.currentAct+1)} →</button><button class="button" data-action="inventory">Gear</button></div>`,'act-milestone');return;}
 if(['won','lost'].includes(s.phase)){const won=s.phase==='won';$('#overlay').innerHTML=modalWrap(`<span class="ending-mark" aria-hidden="true"></span>`+header(won?'Campaign conquered':'Fallen','',won?'FINAL VICTORY · ACT III':`DAY ${s.day}`)+finalOutcomeHTML(s)+`<div class="run-stats"><div class="run-stat"><strong>${s.day}/${CAMPAIGN_LENGTH}</strong><span>Days</span></div><div class="run-stat"><strong class="gold">${s.exact}/${s.kills}</strong><span>Exact</span></div><div class="run-stat"><strong>${s.damageTaken}</strong><span>Damage</span></div></div>${masteryHTML(s)}<div class="actions"><button class="button primary" data-action="new-journey">New run</button><button class="button" data-action="difficulty">Difficulty</button></div>`,`end-state ${won?'victory final-victory':'defeat'}`);return;}
 $('#overlay').innerHTML='';
}
function mutate(fn,...args){if(!state||busy())return false;const ok=fn(state,...args);if(!ok){toast('Unavailable.');return false;}finishRecord();persist();hoverTarget=null;if(!E.getWeapon(state,selected)||E.getWeapon(state,selected).passive){const first=state.slots.findIndex((_,i)=>{const w=E.getWeapon(state,i);return w&&!w.passive});if(first>=0)selected=first;}render();return true}
function chooseWeapon(slot){if(!state||state.phase!=='combat'||modal||busy())return;const w=E.getWeapon(state,slot);if(!w){toast('EMPTY');return;}if(w.passive){toast(`${w.name} · passive`);return;}selected=slot;hoverTarget=null;playerStatus=null;render();if(!E.canUse(state,slot))toast(state.jammedSlots?.includes(slot)?'JAMMED':'NEED ENERGY');}
function fallbackHitSteps(action,before){if(action.hitSteps?.length)return action.hitSteps;if(action.cancelled||action.cancelledByTrap)return [];const enemy=before.enemies?.[action.target];return [{hitIndex:1,target:action.target,raw:action.raw,damage:action.damage,hpBefore:action.before,hpAfter:action.after,armorBefore:enemy?.armor||0,armorAfter:state.enemies?.[action.target]?.armor||0,blocked:Math.max(0,(action.raw||0)-(action.damage||0))}]}
function updatePlayerStatus(){const el=$('#player-status');if(!el||!playerStatus)return;el.innerHTML=`<b>⚔ Hit ${playerStatus.index}/${playerStatus.total}</b><span>${esc(playerStatus.text||'')}</span>`}
async function doAttack(target){if(!state||state.phase!=='combat'||modal||busy())return;const w=E.getWeapon(state,selected);if(!w||w.passive){toast('Select active gear.');return;}if(!E.canUse(state,selected)){toast(state.jammedSlots?.includes(selected)?'JAMMED':'NEED ENERGY');return;}const before=structuredClone(state),preview=E.preview(state,selected,target);attackTarget=preview?.target??target;playerBusy=true;hoverTarget=null;roundStatus=null;clearTimeout(animTimer);
 if(!E.attack(state,selected,target)){playerBusy=false;attackTarget=-1;return;}
 const action=state.lastAction,hitSteps=fallbackHitSteps(action,before),planned=action.plannedHits||Math.max(1,Number(w.hits)||1),actual=action.actualHits??hitSteps.length;
 lastConsequence=G.missedConsequence(state,action,before);
 if(!practiceOrigin){telemetry=G.updateRunTelemetry(telemetry,{type:'attack',beforeState:before,afterState:state,action});if(['camp','milestone','won'].includes(state.phase)){telemetry=G.updateRunTelemetry(telemetry,{type:'roomEnd',afterState:state});recordMastery(state)}finishRecord();persist()}
 roundView=before;roundView.energy=state.energy;playerStatus={index:0,total:Math.max(1,planned),planned,text:'Striking'};render();
 try{
  for(const trap of action.trapSteps||[]){const duration=animationSpeed&&!reducedMotion.matches?430/animationSpeed:0,hero=$('.hero'),message=$('#combat-hint');roundView.hp=trap.hpAfter;roundView.gold=trap.goldAfter;showRoundVitals(trap);hero?.classList.add(trap.damage>0?'enemy-hit':'enemy-blocked');const impact=document.createElement('span');impact.className=`hero-impact${trap.damage>0?'':' blocked'}`;impact.textContent=trap.damage>0?`TRAP −${trap.damage}`:'TRAP BLOCKED';hero?.append(impact);if(message)message.textContent=impact.textContent;if(duration)await pause(duration);hero?.classList.remove('enemy-hit','enemy-blocked');impact.remove()}
  for(const step of hitSteps){playerStatus.index+=1;playerStatus.text=`${step.damage} damage`;updatePlayerStatus();const duration=animationSpeed&&!reducedMotion.matches?430/animationSpeed:0,enemy=$(`.enemy[data-target="${step.target}"]`),hero=$('.hero'),message=$('#combat-hint'),viewEnemy=roundView.enemies?.[step.target];if(viewEnemy){viewEnemy.hp=step.hpAfter;viewEnemy.armor=step.armorAfter;const health=enemy?.querySelector('.enemy-health'),hp=health?.querySelector('span'),bar=enemy?.querySelector('.health-fill'),armor=enemy?.querySelector('.armor-text'),targetButton=enemy?.querySelector('.monster-target'),attackButton=enemy?.querySelector('.attack-action');if(hp)hp.textContent=step.hpAfter;if(health)health.setAttribute('aria-label',`${step.hpAfter} of ${viewEnemy.maxHp} health`);if(bar)bar.style.width=`${Math.max(0,100*step.hpAfter/viewEnemy.maxHp)}%`;if(armor)armor.textContent=`♢ ARMOR ${step.armorAfter}`;const resolving=`${viewEnemy.name}. ${step.hpAfter} of ${viewEnemy.maxHp} health. Resolving hit ${playerStatus.index} of ${playerStatus.total}.`;targetButton?.setAttribute('aria-label',resolving);attackButton?.setAttribute('aria-label',resolving)}
   enemy?.classList.remove('attack-flash');hero?.classList.remove('striking');void enemy?.offsetWidth;enemy?.classList.add('attack-flash');hero?.classList.add('striking');const impact=document.createElement('span');impact.className=`hit-impact${step.blocked?' blocked':''}`;impact.textContent=step.damage?`−${step.damage}`:'BLOCKED';enemy?.append(impact);if(message)message.textContent=`Hit ${playerStatus.index}/${playerStatus.total} · ${step.damage}`;if(duration)await pause(duration);enemy?.classList.remove('attack-flash');hero?.classList.remove('striking');impact.remove();if(duration&&playerStatus.index<hitSteps.length)await pause(90/animationSpeed)}
 }finally{const stopped=actual<planned?` · stopped ${actual}/${planned}`:'',result=action.exact?' · EXACT':action.overkill?` · OVERKILL +${action.overkill}`:'';playerStatus={index:actual,total:Math.max(1,actual),planned,text:`${action.damage||0} damage${stopped}${result}`};roundView=null;playerBusy=false;attackTarget=-1;syncAnimationSpeed();render()}
}
function syncAnimationSpeed(){document.documentElement.style.setProperty('--action-ms',`${animationSpeed?620/animationSpeed:0}ms`);document.documentElement.classList.toggle('animations-off',animationSpeed===0)}
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function roundStepText(step){if(step.type==='attack'){const parts=[`${step.name}: −${step.damage}`];if(step.blocked)parts.push(`♢${step.blocked}`);if(step.stolen)parts.push(`◉−${step.stolen}`);if(step.jamSlot!==undefined&&step.jamSlot!==null)parts.push(`${'QWER'[step.jamSlot]} jammed`);return parts.join(' · ')}if(step.type==='heal')return `${step.name}: +${step.healed||0} HP`;return `${step.name}: wait`}
function roundSummary(action){const parts=(action?.steps||[]).filter(step=>['attack','wait','heal'].includes(step.type)).map(roundStepText);return parts.join(' · ')||'No enemy actions'}
function updateRoundStatus(){const el=$('#round-status');if(!el||!roundStatus)return;el.className=`round-status ${roundStatus.busy?'active':'complete'}`;el.innerHTML=`<b>${roundStatus.busy?'◷':'✓'} ${roundStatus.busy?`Enemy ${roundStatus.index}/${roundStatus.total}`:'Round complete'}</b><span>${esc(roundStatus.text||roundStatus.summary||'')}</span>`}
function showRoundVitals(step){
 roundView.hp=step.hpAfter;roundView.gold=step.goldAfter;
 const health=$('[data-stat="health"] .value'),gold=$('[data-stat="gold"] .value');
 if(health)health.innerHTML=`♥ ${roundView.hp}<span class="muted">/${roundView.maxHp}</span>`;
 if(gold)gold.textContent=`◉ ${roundView.gold}`;
}
async function playEnemyRound(){
 if(!state||state.phase!=='combat'||modal||busy())return;
 const before=structuredClone(state);enemyBusy=true;playerStatus=null;hoverTarget=null;attackTarget=-1;clearTimeout(animTimer);
 if(!E.endTurn(state)){enemyBusy=false;return;}
 if(!practiceOrigin){telemetry=G.updateRunTelemetry(telemetry,{type:'enemyRound',beforeState:before,afterState:state,action:state.lastAction});persist()}
 const steps=(state.lastAction.steps||[]).filter(step=>['attack','wait','heal'].includes(step.type));
 roundStatus={busy:true,index:0,total:steps.length,text:'Resolving'};
 // Commit the round once before playback. Reloading skips the animation, never repeats damage.
 finishRecord();persist();roundView=before;render();
 try{
  for(const step of steps){
   roundStatus.index+=1;roundStatus.text=roundStepText(step);updateRoundStatus();
   const duration=animationSpeed&&!reducedMotion.matches?620/animationSpeed:0;
   const enemy=$(`.enemy[data-target="${step.target}"]`),hero=$('.hero'),message=$('#combat-hint');
   document.documentElement.style.setProperty('--action-ms',`${duration}ms`);
   const cls=step.type==='attack'?'enemy-acting':'enemy-preparing';
   enemy?.classList.add(cls);
   if(message)message.textContent=step.type==='attack'?`${step.name} attacks for ${step.attack}.`:step.label||`${step.name} prepares its next strike.`;
   if(duration)await pause(duration*.42);
   showRoundVitals(step);
   if(step.type==='attack'){
    hero?.classList.add(step.damage>0?'enemy-hit':'enemy-blocked');
    const hit=document.createElement('span');hit.className=`hero-impact${step.damage>0?'':' blocked'}`;hit.textContent=step.damage>0?`−${step.damage}`:'BLOCKED';hero?.append(hit);
    if(message)message.textContent=`${step.name} · ${step.damage} damage${step.blocked?` · ${step.blocked} blocked`:''}${step.stolen?` · ${step.stolen} gold stolen`:''}`;
   }
   if(step.type==='heal'&&step.healTarget!==undefined){
    const healed=roundView.enemies[step.healTarget];if(healed&&step.enemyHpAfter!==undefined)healed.hp=step.enemyHpAfter;
    const recipient=$(`.enemy[data-target="${step.healTarget}"]`);
    const value=recipient?.querySelector('.enemy-health span'),bar=recipient?.querySelector('.health-fill');
    if(value&&healed)value.textContent=healed.hp;if(bar&&healed)bar.style.width=`${100*healed.hp/healed.maxHp}%`;
    if(message)message.textContent=`${step.name} restores ${step.healed||0} health to ${healed?.name||'its companion'}.`;
   }
   if(step.jamSlot!==undefined&&step.jamSlot!==null&&message)message.textContent+=` · ${'QWER'[step.jamSlot]} jammed next turn`;
   if(duration)await pause(duration*.76);
   enemy?.classList.remove(cls);hero?.classList.remove('enemy-hit','enemy-blocked');hero?.querySelector('.hero-impact')?.remove();
   if(duration)await pause(duration*.15);
  }
  }finally{roundStatus={busy:false,summary:roundSummary(state.lastAction)};roundView=null;enemyBusy=false;syncAnimationSpeed();render();}
}
document.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 if(a==='speed'){animationSpeed=[1,2,0][([1,2,0].indexOf(animationSpeed)+1)%3];try{localStorage.setItem(SPEED_KEY,JSON.stringify(animationSpeed));}catch{}syncAnimationSpeed();b.textContent=motionLabel();b.setAttribute('aria-label',motionLabel());return;}
 if(busy())return;
 if(a==='import-legacy'){const imported=E.restoreRun(read(LEGACY_SAVE_KEY));if(!imported){toast('Act I save could not be imported.');return;}state=imported;selectedDifficulty=state.difficulty||'pilgrim';telemetry=G.initialRunTelemetry();intro=false;modal=null;selected=state.slots.findIndex((_,i)=>{const w=E.getWeapon(state,i);return w&&!w.passive});if(selected<0)selected=0;draftPicks=[];roundStatus=null;playerStatus=null;lastConsequence=null;if(state.phase==='combat')telemetry=G.updateRunTelemetry(telemetry,{type:'encounterStart',afterState:state});persist();render();return;}
 if(a==='start'){state=E.newRun(Date.now(),selectedDifficulty);telemetry=G.initialRunTelemetry();intro=false;modal=null;selected=0;draftPicks=[];roundStatus=null;playerStatus=null;lastConsequence=null;persist();render();return;}
 if(a==='draft-pick'){const i=+b.dataset.index;if(draftPicks.includes(i))draftPicks=draftPicks.filter(n=>n!==i);else if(draftPicks.length<2)draftPicks.push(i);else{toast('Choose two items. Deselect one to change your choice.');return;}renderOverlay();return;}
 if(a==='draft-confirm'){if(mutate(E.selectStartingItems,draftPicks)){selected=0;draftPicks=[];telemetry=G.updateRunTelemetry(telemetry,{type:'encounterStart',afterState:state});persist();render();}return;}
 if(a==='exit-practice'){if(!practiceOrigin)return;state=practiceOrigin;practiceOrigin=null;selected=state.slots.findIndex((_,i)=>{const w=E.getWeapon(state,i);return w&&!w.passive});if(selected<0)selected=0;modal=null;roundStatus=null;playerStatus=null;lastConsequence=null;persist();render();return;}
 if(a==='inspect'){inspectedTarget=+b.dataset.target;modal='inspect';hoverTarget=null;renderOverlay();return;}
 if(a==='select'){chooseWeapon(+b.dataset.slot);return;}if(a==='attack'){doAttack(+b.dataset.target);return;}
 if(a==='end-turn'){lastConsequence=null;playEnemyRound();return;}if(a==='next-day'){selected=state.slots.findIndex((_,i)=>{const w=E.getWeapon(state,i);return w&&!w.passive});roundStatus=null;playerStatus=null;lastConsequence=null;if(mutate(E.nextDay)&&state.phase==='combat'){telemetry=G.updateRunTelemetry(telemetry,{type:'encounterStart',afterState:state});persist();render();}return;}
 if(a==='continue-act'){selected=state.slots.findIndex((_,i)=>{const w=E.getWeapon(state,i);return w&&!w.passive});roundStatus=null;playerStatus=null;lastConsequence=null;if(mutate(E.continueAct)){telemetry=G.updateRunTelemetry(telemetry,{type:'encounterStart',afterState:state});persist();render();}return;}
 if(a==='event'){mutate(E.chooseEvent,+b.dataset.index);return;}
 if(a==='resolve-drop'){mutate(E.resolveDrop,+b.dataset.slot);return;}if(a==='leave-drop'){mutate(E.resolveDrop,null);return;}
 if(a==='close'){modal=null;renderOverlay();return;}if(['help','menu','inventory','difficulty'].includes(a)){modal=a;renderOverlay();return;}
 if(a==='difficulty-select'){selectedDifficulty=b.dataset.id;renderOverlay();return;}
 if(a==='restart-confirm'){modal='restart';renderOverlay();return;}if(a==='abandon'||a==='new-journey'){state=null;intro=true;modal=null;roundStatus=null;playerStatus=null;try{localStorage.removeItem(SAVE_KEY)}catch{}render();return;}
});
document.addEventListener('pointerover',event=>{if(!state||state.phase!=='combat'||modal||busy())return;const target=event.target.closest('[data-target]');if(target&&target.dataset.target!==undefined){hoverTarget=+target.dataset.target;const el=$('#combat-hint');if(el)el.textContent=hint(state);}});
document.addEventListener('pointerout',event=>{if(event.target.closest('[data-target]')&&!event.relatedTarget?.closest?.(`[data-target="${hoverTarget}"]`)){hoverTarget=null;const el=$('#combat-hint');if(el&&state&&!busy())el.textContent=hint(state)}});
document.addEventListener('focusin',event=>{if(!state||state.phase!=='combat'||modal||busy())return;const target=event.target.closest('[data-target]');if(target&&target.dataset.target!==undefined){hoverTarget=+target.dataset.target;target.closest('.enemy')?.classList.add('targeted');const el=$('#combat-hint');if(el)el.textContent=hint(state)}});
document.addEventListener('focusout',event=>{const enemy=event.target.closest('.enemy');if(enemy&&!enemy.contains(event.relatedTarget)){enemy.classList.remove('targeted');hoverTarget=null;const el=$('#combat-hint');if(el&&state&&!busy())el.textContent=hint(state)}});
document.addEventListener('keydown',event=>{if(event.key===' '&&(busy()||(!modal&&!intro&&state?.phase==='combat')))event.preventDefault();if(event.repeat||event.ctrlKey||event.metaKey||event.altKey)return;if(busy())return;if(event.key==='Escape'){if(modal)modal=null;else if(!intro)modal='menu';renderOverlay();return;}if(modal||intro||state?.phase!=='combat')return;const k=event.key.toLowerCase();if('qwer'.includes(k)&&k.length===1){event.preventDefault();chooseWeapon('qwer'.indexOf(k));}else if('123'.includes(k)&&k.length===1){event.preventDefault();doAttack(+k-1);}else if(k===' '){event.preventDefault();playEnemyRound();}});
const overlayObserver=new MutationObserver(()=>{const dialog=$('#overlay .modal');$('#app').inert=!!dialog;if(dialog){const heading=dialog.querySelector('h2,h1');if(heading){heading.id='dialog-heading';dialog.setAttribute('aria-labelledby','dialog-heading')}const first=dialog.querySelector('button:not(:disabled)');if(first&&!dialog.contains(document.activeElement))first.focus({preventScroll:true});}});
overlayObserver.observe($('#overlay'),{childList:true});
document.addEventListener('keydown',event=>{if(event.key!=='Tab')return;const dialog=$('#overlay .modal');if(!dialog)return;const buttons=[...dialog.querySelectorAll('button:not(:disabled),a[href],input')];if(!buttons.length)return;const first=buttons[0],last=buttons.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});
reducedMotion.addEventListener?.('change',()=>{syncAnimationSpeed();render()});
if(state?.phase==='combat'&&telemetry.roomStart?.day!==state.day){telemetry=G.updateRunTelemetry(telemetry,{type:'encounterStart',afterState:state});persist()}
syncAnimationSpeed();finishRecord();render();

