// ART-002 presentation-only catalog mapping. Generated by assets/build-equipment-art.mjs.
export const EQUIPMENT_ART = {
  "rusty_dagger": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      0,
      0,
      314,
      309
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-rusty-dagger",
    "grip": [
      0.2995222929936306,
      0.7304854368932039
    ],
    "rotation": 0,
    "heldScale": 61,
    "identity": "Bent awl",
    "act": 1,
    "slot": "weapon"
  },
  "rusty_sword": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      314,
      0,
      313,
      309
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-rusty-sword",
    "grip": [
      0.27043130990415337,
      0.7913592233009709
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Broken notched sword",
    "act": 1,
    "slot": "weapon"
  },
  "rusty_spear": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      627,
      0,
      314,
      309
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-rusty-spear",
    "grip": [
      0.22963375796178345,
      0.7812135922330098
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Flint on crooked pole",
    "act": 1,
    "slot": "weapon"
  },
  "rusty_axe": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      941,
      0,
      313,
      309
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-rusty-axe",
    "grip": [
      0.35055910543130986,
      0.7406310679611651
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Rope hatchet",
    "act": 1,
    "slot": "weapon"
  },
  "rusty_hammer": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      0,
      309,
      314,
      300
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-rusty-hammer",
    "grip": [
      0.33945859872611467,
      0.7899666666666667
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Lashed stone hammer",
    "act": 1,
    "slot": "weapon"
  },
  "rusty_knife": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      314,
      309,
      313,
      300
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-rusty-knife",
    "grip": [
      0.2604153354632588,
      0.8108666666666666
    ],
    "rotation": 0,
    "heldScale": 61,
    "identity": "Chipped kitchen knife",
    "act": 1,
    "slot": "weapon"
  },
  "rusty_flurry": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      627,
      309,
      314,
      300
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-rusty-flurry",
    "grip": [
      0.33945859872611467,
      0.8108666666666666
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Scrap trident",
    "act": 1,
    "slot": "weapon"
  },
  "rusty_twins": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      941,
      309,
      313,
      300
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-rusty-twins",
    "grip": [
      0.28044728434504795,
      0.7899666666666667
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Two hatchets",
    "act": 1,
    "slot": "weapon"
  },
  "dagger": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      0,
      609,
      314,
      311
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-dagger",
    "grip": [
      0.6689331210191083,
      0.22924437299035358
    ],
    "rotation": 180,
    "heldScale": 61,
    "identity": "Eye-pommel bone needle",
    "act": 1,
    "slot": "weapon"
  },
  "sword": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      314,
      609,
      313,
      311
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-sword",
    "grip": [
      0.2604153354632588,
      0.8441479099678456
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Riveted iron sword",
    "act": 1,
    "slot": "weapon"
  },
  "axe": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      627,
      609,
      314,
      311
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-axe",
    "grip": [
      0.4093471337579618,
      0.8038263665594856
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Holed charred crescent axe",
    "act": 1,
    "slot": "weapon"
  },
  "spear": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      941,
      609,
      313,
      311
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-spear",
    "grip": [
      0.2103354632587859,
      0.8340675241157556
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Rag-flag walking spear",
    "act": 1,
    "slot": "weapon"
  },
  "hammer": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      0,
      920,
      314,
      334
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-hammer",
    "grip": [
      0.2795541401273886,
      0.7762275449101796
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Bell-headed hammer",
    "act": 1,
    "slot": "weapon"
  },
  "buckler": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      314,
      920,
      313,
      334
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-buckler",
    "grip": [
      0.30047923322683706,
      0.738682634730539
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Three-plank buckler",
    "act": 1,
    "slot": "offhand"
  },
  "war_pick": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      627,
      920,
      314,
      334
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-war-pick",
    "grip": [
      0.2595859872611465,
      0.7949999999999999
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Crowbill pick",
    "act": 1,
    "slot": "weapon"
  },
  "twin_fangs": {
    "file": "assets/equipment-act1-a-v2.png",
    "crop": [
      941,
      920,
      313,
      334
    ],
    "atlas": [
      1254,
      1254
    ],
    "className": "item-art-twin-fangs",
    "grip": [
      0.27043130990415337,
      0.7480688622754491
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Crossed ivory fangs",
    "act": 1,
    "slot": "weapon"
  },
  "cinder_flail": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      0,
      0,
      324,
      319
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-cinder-flail",
    "grip": [
      0.3597777777777778,
      0.649362591431557
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Two-weight chain flail",
    "act": 1,
    "slot": "weapon"
  },
  "needle_rain": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      324,
      0,
      324,
      319
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-needle-rain",
    "grip": [
      0.38975925925925925,
      0.7203866248693834
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Three rag-fletched darts",
    "act": 1,
    "slot": "weapon"
  },
  "splitting_axe": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      648,
      0,
      323,
      319
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-splitting-axe",
    "grip": [
      0.32079256965944275,
      0.7406792058516196
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Split wedge axe",
    "act": 1,
    "slot": "weapon"
  },
  "ritual_rod": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      971,
      0,
      324,
      319
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-ritual-rod",
    "grip": [
      0.5896358024691357,
      0.7406792058516196
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Bone disk ritual fork",
    "act": 1,
    "slot": "weapon"
  },
  "cook_cleaver": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      1295,
      0,
      324,
      319
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-cook-cleaver",
    "grip": [
      0.2798271604938272,
      0.7102403343782653
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Holed butcher cleaver",
    "act": 1,
    "slot": "weapon"
  },
  "powder_spike": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      0,
      319,
      324,
      288
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-powder-spike",
    "grip": [
      0.3997530864197531,
      0.7029050925925924
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Flask spike",
    "act": 1,
    "slot": "weapon"
  },
  "ash_leathers": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      324,
      319,
      324,
      288
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-ash-leathers",
    "grip": [
      0.2998148148148148,
      0.8265277777777776
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "One-shoulder patched vest",
    "act": 1,
    "slot": "body"
  },
  "butcher_apron": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      648,
      319,
      323,
      288
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-butcher-apron",
    "grip": [
      0.30074303405572755,
      0.8265277777777776
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Long torn apron",
    "act": 1,
    "slot": "body"
  },
  "knife_guard": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      971,
      319,
      324,
      288
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-knife-guard",
    "grip": [
      0.2998148148148148,
      0.8265277777777776
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Three-tooth guard",
    "act": 1,
    "slot": "offhand"
  },
  "falchion": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      1295,
      319,
      324,
      288
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-falchion",
    "grip": [
      0.30980864197530866,
      0.7141435185185183
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Serrated curved falchion",
    "act": 1,
    "slot": "weapon"
  },
  "fang": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      0,
      607,
      324,
      364
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-fang",
    "grip": [
      0.33979012345679016,
      0.6078388278388278
    ],
    "rotation": 0,
    "heldScale": 61,
    "identity": "Bottle-glass dagger",
    "act": 1,
    "slot": "weapon"
  },
  "glaive": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      324,
      607,
      324,
      364
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-glaive",
    "grip": [
      0.3198024691358025,
      0.6345146520146521
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Crescent polearm",
    "act": 1,
    "slot": "weapon"
  },
  "greatsword": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      648,
      607,
      323,
      364
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-greatsword",
    "grip": [
      0.25061919504643965,
      0.6700824175824175
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Squared perforated greatsword",
    "act": 1,
    "slot": "weapon"
  },
  "plate": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      971,
      607,
      324,
      364
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-plate",
    "grip": [
      0.2998148148148148,
      0.75010989010989
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Cross-braced plate",
    "act": 1,
    "slot": "body"
  },
  "bonehammer": {
    "file": "assets/equipment-act1-b-v3.png",
    "crop": [
      1295,
      607,
      324,
      364
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-bonehammer",
    "grip": [
      0.2598395061728395,
      0.6611904761904761
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Bone-bundle maul",
    "act": 1,
    "slot": "weapon"
  },
  "knight_lance": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      0,
      0,
      324,
      309
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-knight-lance",
    "grip": [
      0.26983333333333337,
      0.7960733549083064
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Pennant iron lance",
    "act": 1,
    "slot": "weapon"
  },
  "oathblade": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      324,
      0,
      324,
      309
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-oathblade",
    "grip": [
      0.34978395061728396,
      0.7541747572815534
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Asymmetric oath guard",
    "act": 1,
    "slot": "weapon"
  },
  "headsman_axe": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      648,
      0,
      323,
      309
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-headsman-axe",
    "grip": [
      0.37091640866873066,
      0.7541747572815534
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Holed half-circle axe",
    "act": 1,
    "slot": "weapon"
  },
  "redjaw_cleaver": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      971,
      0,
      324,
      309
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-redjaw-cleaver",
    "grip": [
      0.37976543209876545,
      0.7437001078748651
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Toothed jaw cleaver",
    "act": 1,
    "slot": "weapon"
  },
  "bell_flail": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      1295,
      0,
      324,
      309
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-bell-flail",
    "grip": [
      0.2598395061728395,
      0.7227508090614885
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Three hanging bells",
    "act": 1,
    "slot": "weapon"
  },
  "ossuary_knuckles": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      0,
      309,
      324,
      302
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-ossuary-knuckles",
    "grip": [
      0.47970370370370374,
      0.6391280353200882
    ],
    "rotation": 0,
    "heldScale": 44,
    "identity": "Four-hole bone knuckles",
    "act": 1,
    "slot": "weapon"
  },
  "moon_needles": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      324,
      309,
      324,
      302
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-moon-needles",
    "grip": [
      0.40974691358024684,
      0.6069757174392936
    ],
    "rotation": 180,
    "heldScale": 88,
    "identity": "Three crescent needles",
    "act": 1,
    "slot": "weapon"
  },
  "hex_focus": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      648,
      309,
      323,
      302
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-hex-focus",
    "grip": [
      0.30074303405572755,
      0.7998896247240616
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Hexagonal cage focus",
    "act": 1,
    "slot": "weapon"
  },
  "trap_hook": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      971,
      309,
      324,
      302
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-trap-hook",
    "grip": [
      0.23985185185185187,
      0.7998896247240616
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Ratchet hook",
    "act": 1,
    "slot": "weapon"
  },
  "powder_cannon": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      1295,
      309,
      324,
      302
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-powder-cannon",
    "grip": [
      0.289820987654321,
      0.7891721854304633
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Barrel bayonet",
    "act": 1,
    "slot": "weapon"
  },
  "grave_mace": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      0,
      611,
      324,
      360
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-grave-mace",
    "grip": [
      0.2798271604938272,
      0.6754074074074073
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Gravestone mace",
    "act": 1,
    "slot": "weapon"
  },
  "vow_greatblade": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      324,
      611,
      324,
      360
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-vow-greatblade",
    "grip": [
      0.289820987654321,
      0.7023796296296296
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Broad jagged vow blade",
    "act": 1,
    "slot": "weapon"
  },
  "tower_shield": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      648,
      611,
      323,
      360
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-tower-shield",
    "grip": [
      0.30074303405572755,
      0.7473333333333332
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Coffin tower shield",
    "act": 1,
    "slot": "offhand"
  },
  "chainmail": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      971,
      611,
      324,
      360
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-chainmail",
    "grip": [
      0.2998148148148148,
      0.7473333333333332
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Diagonal-sash mail",
    "act": 1,
    "slot": "body"
  },
  "painward_mail": {
    "file": "assets/equipment-act1-c-v2.png",
    "crop": [
      1295,
      611,
      324,
      360
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-painward-mail",
    "grip": [
      0.2998148148148148,
      0.7473333333333332
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Shaggy toggled hide",
    "act": 1,
    "slot": "body"
  },
  "prism_needle": {
    "file": "assets/equipment-act2-v2.png",
    "crop": [
      13,
      13,
      336,
      329
    ],
    "atlas": [
      1448,
      1086
    ],
    "className": "item-art-prism-needle",
    "grip": [
      0.25220238095238096,
      0.7527051671732522
    ],
    "rotation": 0,
    "heldScale": 61,
    "identity": "Thin triangular needle",
    "act": 2,
    "slot": "weapon"
  },
  "facet_blade": {
    "file": "assets/equipment-act2-v2.png",
    "crop": [
      375,
      13,
      336,
      329
    ],
    "atlas": [
      1448,
      1086
    ],
    "className": "item-art-facet-blade",
    "grip": [
      0.20910714285714288,
      0.7967173252279636
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Split-diamond sword",
    "act": 2,
    "slot": "weapon"
  },
  "shard_spear": {
    "file": "assets/equipment-act2-v2.png",
    "crop": [
      737,
      13,
      336,
      329
    ],
    "atlas": [
      1448,
      1086
    ],
    "className": "item-art-shard-spear",
    "grip": [
      0.1767857142857143,
      0.7967173252279636
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Triple shard pole",
    "act": 2,
    "slot": "weapon"
  },
  "geode_maul": {
    "file": "assets/equipment-act2-v2.png",
    "crop": [
      1099,
      13,
      336,
      329
    ],
    "atlas": [
      1448,
      1086
    ],
    "className": "item-art-geode-maul",
    "grip": [
      0.1875595238095238,
      0.8077203647416413
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Hollow geode maul",
    "act": 2,
    "slot": "weapon"
  },
  "shard_hook": {
    "file": "assets/equipment-act2-v2.png",
    "crop": [
      13,
      368,
      336,
      323
    ],
    "atlas": [
      1448,
      1086
    ],
    "className": "item-art-shard-hook",
    "grip": [
      0.21988095238095237,
      0.7659442724458204
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Open crescent crystal hook",
    "act": 2,
    "slot": "weapon"
  },
  "prism_focus": {
    "file": "assets/equipment-act2-v2.png",
    "crop": [
      375,
      368,
      336,
      323
    ],
    "atlas": [
      1448,
      1086
    ],
    "className": "item-art-prism-focus",
    "grip": [
      0.20910714285714288,
      0.788359133126935
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Floating diamond focus",
    "act": 2,
    "slot": "weapon"
  },
  "mirror_shield": {
    "file": "assets/equipment-act2-v2.png",
    "crop": [
      737,
      368,
      336,
      323
    ],
    "atlas": [
      1448,
      1086
    ],
    "className": "item-art-mirror-shield",
    "grip": [
      0.2845238095238095,
      0.788359133126935
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Three-spoke mirror shield",
    "act": 2,
    "slot": "offhand"
  },
  "lattice_mail": {
    "file": "assets/equipment-act2-v2.png",
    "crop": [
      1099,
      368,
      336,
      323
    ],
    "atlas": [
      1448,
      1086
    ],
    "className": "item-art-lattice-mail",
    "grip": [
      0.2845238095238095,
      0.788359133126935
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Open lattice tunic",
    "act": 2,
    "slot": "body"
  },
  "crystal_hide": {
    "file": "assets/equipment-act2-v2.png",
    "crop": [
      13,
      717,
      336,
      356
    ],
    "atlas": [
      1448,
      1086
    ],
    "className": "item-art-crystal-hide",
    "grip": [
      0.2845238095238095,
      0.7517977528089888
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Asymmetric crystal scales",
    "act": 2,
    "slot": "body"
  },
  "moth_silk": {
    "file": "assets/equipment-act2-v2.png",
    "crop": [
      375,
      717,
      336,
      356
    ],
    "atlas": [
      1448,
      1086
    ],
    "className": "item-art-moth-silk",
    "grip": [
      0.2845238095238095,
      0.7517977528089888
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Moth-eye silk mantle",
    "act": 2,
    "slot": "body"
  },
  "archon_facet": {
    "file": "assets/equipment-act2-v2.png",
    "crop": [
      737,
      717,
      336,
      356
    ],
    "atlas": [
      1448,
      1086
    ],
    "className": "item-art-archon-facet",
    "grip": [
      0.1767857142857143,
      0.8331460674157304
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Crowned orbiting facets",
    "act": 2,
    "slot": "weapon"
  },
  "hell_fang": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      0,
      0,
      324,
      324
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-hell-fang",
    "grip": [
      0.3297962962962963,
      0.6493312757201646
    ],
    "rotation": 0,
    "heldScale": 61,
    "identity": "Hooked obsidian tooth",
    "act": 3,
    "slot": "weapon"
  },
  "ember_fork": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      324,
      0,
      324,
      324
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-ember-fork",
    "grip": [
      0.2998148148148148,
      0.7292489711934156
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Ember trident",
    "act": 3,
    "slot": "weapon"
  },
  "chain_hook": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      648,
      0,
      323,
      324
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-chain-hook",
    "grip": [
      0.2004953560371517,
      0.6992798353909464
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Chain arc hook",
    "act": 3,
    "slot": "weapon"
  },
  "obsidian_lance": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      971,
      0,
      324,
      324
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-obsidian-lance",
    "grip": [
      0.20987037037037037,
      0.739238683127572
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Single long obsidian point",
    "act": 3,
    "slot": "weapon"
  },
  "hell_cleaver": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      1295,
      0,
      324,
      324
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-hell-cleaver",
    "grip": [
      0.23985185185185187,
      0.6992798353909464
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Notched black cleaver",
    "act": 3,
    "slot": "weapon"
  },
  "furnace_maul": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      0,
      324,
      324,
      324
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-furnace-maul",
    "grip": [
      0.26983333333333337,
      0.6892901234567899
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Barred furnace maul",
    "act": 3,
    "slot": "weapon"
  },
  "ember_focus": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      324,
      324,
      324,
      324
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-ember-focus",
    "grip": [
      0.2198641975308642,
      0.7592181069958848
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Suspended ember fork",
    "act": 3,
    "slot": "weapon"
  },
  "oath_blade_infernal": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      648,
      324,
      323,
      324
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-oath-blade",
    "grip": [
      0.2004953560371517,
      0.7292489711934156
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Horn-guard oath sword",
    "act": 3,
    "slot": "weapon"
  },
  "brand_guard": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      971,
      324,
      324,
      324
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-brand-guard",
    "grip": [
      0.2998148148148148,
      0.7192592592592592
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Round branded shield",
    "act": 3,
    "slot": "offhand"
  },
  "branded_hide": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      1295,
      324,
      324,
      324
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-branded-hide",
    "grip": [
      0.2998148148148148,
      0.7192592592592592
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Burnt crossing-brand hide",
    "act": 3,
    "slot": "body"
  },
  "ribbed_hide": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      0,
      648,
      324,
      323
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-ribbed-hide",
    "grip": [
      0.2998148148148148,
      0.7183900928792568
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Five pale rib bands",
    "act": 3,
    "slot": "body"
  },
  "black_plate": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      324,
      648,
      324,
      323
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-black-plate",
    "grip": [
      0.2998148148148148,
      0.7183900928792568
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Fractured obsidian plate",
    "act": 3,
    "slot": "body"
  },
  "horn_shield": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      648,
      648,
      323,
      323
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-horn-shield",
    "grip": [
      0.30074303405572755,
      0.7183900928792568
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Pale horn rim",
    "act": 3,
    "slot": "offhand"
  },
  "bone_cage": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      971,
      648,
      324,
      323
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-bone-cage",
    "grip": [
      0.2998148148148148,
      0.7183900928792568
    ],
    "rotation": 0,
    "heldScale": 62,
    "identity": "Open rib cage",
    "act": 3,
    "slot": "body"
  },
  "heart_obsidian": {
    "file": "assets/equipment-infernal-v1.png",
    "crop": [
      1295,
      648,
      324,
      323
    ],
    "atlas": [
      1619,
      971
    ],
    "className": "item-art-heart-obsidian",
    "grip": [
      0.19987654320987655,
      0.7183900928792568
    ],
    "rotation": 0,
    "heldScale": 88,
    "identity": "Three-lobed hollow heart axe",
    "act": 3,
    "slot": "weapon"
  }
};
